version: "3.4"
services:
  services_app:
    container_name: ${CONTAINER_NAME}
    build: .
    restart: always
    network_mode: "host"
    volumes:
      - ${ENVIRONMENT_PATH}:/home/cun_repository_docker/
